[project]
name = "bokunano"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.16.8",
]
instruction-generation = [
    "accelerate==1.15.0",
    "autoawq==0.2.9",
    "torch==2.13.0",
    "transformers==4.51.3",
]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
