"""Export the human-approved release dictionary for the demo parser."""
import csv
import hashlib
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'data/instruction_dictionaries/release/japanese_atomic_expressions.csv'
PROVENANCE = ROOT / 'data/instruction_dictionaries/release/japanese_atomic_expression_provenance.jsonl'
OUTPUT = ROOT / 'web/approved-expressions.js'
# Match the dictionary's AST to the demo's AST, not Japanese labels or row order.
js = """
import { CNL_OPERATIONS } from './web/cnl.js';
import { captureSemanticAst } from './web/semantic-ast.js';
console.log(JSON.stringify(CNL_OPERATIONS.map(op => [op.id, captureSemanticAst({valid:true,operations:[op]})])));
"""
operations = json.loads(subprocess.check_output(['node', '--input-type=module', '-e', js], cwd=ROOT, text=True))
key = lambda x: json.dumps(x, sort_keys=True, ensure_ascii=False)
by_ast = {key(ast): ident for ident, ast in operations}
provenance = {r['expression_id']: r for r in map(json.loads, PROVENANCE.read_text().splitlines())}
rows = list(csv.DictReader(SOURCE.open()))
forms = {ident: [] for ident, _ in operations}
seen = {}
for row in rows:
    proof = provenance[row['expression_id']]
    assert row['expression_ja'] == proof['approved_expression_ja']
    assert row['connective_expression_ja'] == proof['approved_connective_expression_ja']
    ident = by_ast[key(json.loads(row['operation_ast']))]
    for field in ['expression_ja', 'connective_expression_ja']:
        phrase = row[field]
        assert seen.get(phrase, ident) == ident, ('Ambiguous expression', phrase)
        if phrase not in forms[ident]:
            forms[ident].append(phrase)
        seen[phrase] = ident
metadata = {'source': str(SOURCE.relative_to(ROOT)), 'source_sha256': hashlib.sha256(SOURCE.read_bytes()).hexdigest(), 'approved_records': len(rows), 'unique_forms': len(seen), 'operations': len(forms)}
content = '// Generated by scripts/model/build_web_approved_expressions.py; do not edit by hand.\n'
content += 'export const APPROVED_EXPRESSION_METADATA = Object.freeze(' + json.dumps(metadata, ensure_ascii=False, indent=2) + ');\n'
content += 'export const APPROVED_OPERATION_EXPRESSIONS = Object.freeze(' + json.dumps(forms, ensure_ascii=False, indent=2) + ');\n'
if '--check' in sys.argv:
    assert OUTPUT.read_text() == content, 'Approved dictionary export is stale'
else:
    OUTPUT.write_text(content)
print(f'{len(rows)} approved records, {len(seen)} unique forms, {len(forms)} operations')
